# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ecb764c45596c3cda180a4ee94bd6a17"
name = "Moonora"
handle = "moonora"
application_url = "https://phpstack-1380969-5101925.cloudwaysapps.com/"
embedded = true

[build]
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://phpstack-1380969-5101925.cloudwaysapps.com/authenticate"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
