# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b4b00e373e98f7e80b6cf9c3d33b2e52"
name = "Pairbo Private"
handle = "pairbo-private"
application_url = "https://c9a4-182-178-161-142.ngrok-free.app/"
embedded = true

[build]
include_config_on_deploy = true

[auth]
redirect_urls = [ "https://c9a4-182-178-161-142.ngrok-free.app/authenticate" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
