# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1d31760f8c715e364f77bb349aac5275"
name = "Pairbo V2"
handle = "pairbo-v2"
application_url = "https://phpstack-1169091-4354155.cloudwaysapps.com/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://phpstack-1169091-4354155.cloudwaysapps.com/authenticate"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
