# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "146cc189bbcbf630eb366d31873fe1fc"
name = "pairbo-staging"
handle = "pairbo-test"
application_url = "https://phpstack-1169091-4354155.cloudwaysapps.com/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://phpstack-1169091-4354155.cloudwaysapps.com/authenticate"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
